services:
  gateway-service:
    build: 
      context: gateway-service
      dockerfile: Dockerfile
    env_file:
      - ./gateway-service/.env
    networks:
      - test-network
    ports:
      - "8002:8002"
    depends_on:
      - auth-service
      - menu-service


  auth-service:
    build: 
      context: auth-service
      dockerfile: Dockerfile
    env_file:
      - ./auth-service/.env
    networks:
      - test-network
    depends_on:
      - auth-db
    volumes:
      - ./auth-service:/app

  auth-db:
    image: mongo:5.0
    container_name: auth-db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: auth_db
    volumes:
      - auth_mongodb_data:/data/db
      - ./auth-service/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - test-network

  menu-service:
    build: 
      context: menu-service
      dockerfile: Dockerfile
    env_file:
      - ./menu-service/.env
    networks:
      - test-network
    depends_on:
      - menu-db
    volumes:
      - ./menu-service:/app

  menu-db:
    image: mongo:5.0
    container_name: menu-db
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: menu_db
    volumes:
      - menu_mongodb_data:/data/db
      - ./menu-service/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - test-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@auth-db:27017,menu-db:27017/
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: passwordmongo
    networks:
      - test-network
    depends_on:
      - auth-db
      - menu-db
      
networks:
  test-network:
    driver: bridge

volumes:
  auth_mongodb_data:
  menu_mongodb_data:
  
